version: '3.5'
services:
  restapi:
    build: ./restapi
    ports:
    - "5000:5000"
  webapp:
    build: ./webapp
    ports:
    - "8080:8080"
    depends_on:
      - restapi
    healthcheck:
      test: ["curl -f localhost:5000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s